name: full_auto_deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Build image
      - name: Build Docker Image
        run: docker build -t myapp .

      # 3. Login DockerHub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 4. Tag
      - name: Tag Image
        run: docker tag myapp mosesclouddev/for_ci_cd_pipeline

      # 5. Push
      - name: Push Image
        run: docker push mosesclouddev/for_ci_cd_pipeline

      # 6. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull mosesclouddev/for_ci_cd_pipeline
            sudo docker stop mycontainer || true
            sudo docker rm mycontainer || true
            sudo docker run -d -p 8000:8000 --name mycontainer mosesclouddev/for_ci_cd_pipeline