name: basic_pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: creating docker image
        run: docker build -t app .

      - name: check python syntax
        run: python -m py_compile app.py
